name: buld&test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Build Sucessful!"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Test Sucessful!"
